# The URL the site will be built for
base_url = "https://blog.azanulhaque.dev"

theme = "feather"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

taxonomies = [{ name = "tags", feed = true }]

# RSS and ATOM feed generation
generate_feeds = true
feed_filenames = ["rss.xml"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
    { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
# Put all your custom variables here
feather_head = """<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-X32Y0RRH8C"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-X32Y0RRH8C');
</script>"""
